import { useState, useRef } from 'react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Label } from '@/components/ui/label';
import { Loader2, Linkedin, Upload, FileText, AlertCircle } from 'lucide-react';
import { ParsedResume } from '@shared/types';
import { toast } from 'sonner';
import { parseResumeText } from '@/lib/resumeParser';
import { trpc } from '@/lib/trpc';
import { Alert, AlertDescription } from '@/components/ui/alert';

interface ResumeLinkedInImporterProps {
  onImported: (data: ParsedResume) => void;
}

export default function ResumeLinkedInImporter({ onImported }: ResumeLinkedInImporterProps) {
  const [pastedText, setPastedText] = useState('');
  const [loading, setLoading] = useState(false);
  const [file, setFile] = useState<File | null>(null);
  const [fileError, setFileError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const parseMutation = trpc.resume.parse.useMutation();

  const handleTextImport = () => {
    if (!pastedText.trim()) {
      toast.error('Please paste your LinkedIn profile text.');
      return;
    }

    setLoading(true);
    setTimeout(() => {
      try {
        const parsed = parseResumeText(pastedText);
        toast.success('Successfully imported and parsed LinkedIn profile!');
        onImported(parsed);
      } catch (err) {
        toast.error('Failed to parse text. Please check the content and try again.');
      } finally {
        setLoading(false);
      }
    }, 1500);
  };

  const handleFileSelect = (e: React.ChangeEvent<HTMLInputElement>) => {
    const selectedFile = e.target.files?.[0];
    if (selectedFile) {
      if (selectedFile.type !== 'application/pdf' && selectedFile.type !== 'text/plain') {
        toast.error('Please upload a PDF profile export or TXT file.');
        return;
      }
      setFile(selectedFile);
      setFileError(null);
    }
  };

  const handleFileImport = async () => {
    if (!file) return;

    setLoading(true);
    setFileError(null);

    if (file.type === 'text/plain') {
      const reader = new FileReader();
      reader.onload = (e) => {
        try {
          const text = e.target?.result as string;
          const parsed = parseResumeText(text);
          toast.success('Successfully parsed LinkedIn profile file!');
          onImported(parsed);
        } catch (err) {
          toast.error('Failed to parse file content.');
        } finally {
          setLoading(false);
        }
      };
      reader.onerror = () => {
        toast.error('Failed to read file.');
        setLoading(false);
      };
      reader.readAsText(file);
    } else {
      // PDF files: send to server for proper parsing (never fabricate data)
      try {
        const reader = new FileReader();
        reader.onload = async (e) => {
          try {
            const result = e.target?.result as string;
            const base64 = result.split(',')[1];
            if (!base64) {
              throw new Error('Failed to read PDF file as base64.');
            }

            const parsed = await parseMutation.mutateAsync({
              filename: file.name,
              base64,
            });

            // Ensure the LinkedIn profile source is marked
            if (!parsed.header?.links?.some(l => l.label === 'LinkedIn')) {
              parsed.header = parsed.header || {};
              parsed.header.links = [
                ...(parsed.header.links || []),
                { label: 'LinkedIn', url: 'https://linkedin.com/in/imported-profile' }
              ];
            }

            toast.success('Successfully parsed LinkedIn profile PDF!');
            onImported(parsed);
          } catch (err: any) {
            console.error('LinkedIn PDF parsing error:', err);
            setFileError(
              err?.message || 'Failed to parse PDF. Please paste your profile text instead.'
            );
          } finally {
            setLoading(false);
          }
        };
        reader.onerror = () => {
          setFileError('Failed to read PDF file.');
          setLoading(false);
        };
        reader.readAsDataURL(file);
      } catch (err: any) {
        setFileError(err?.message || 'Failed to process PDF file.');
        setLoading(false);
      }
    }
  };

  return (
    <Card className="border-slate-200">
      <CardHeader>
        <CardTitle className="flex items-center gap-2 text-blue-600">
          <Linkedin className="w-5 h-5 fill-current" />
          Import from LinkedIn
        </CardTitle>
        <CardDescription>
          Paste your LinkedIn profile text or upload the profile PDF export (generated by clicking "More" &gt; "Save to PDF" on LinkedIn).
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-6">
        <div className="space-y-2">
          <Label htmlFor="linkedin-text">Paste Profile Text</Label>
          <Textarea
            id="linkedin-text"
            placeholder="Paste your About section, experience cards, and skills here..."
            rows={5}
            value={pastedText}
            onChange={(e) => setPastedText(e.target.value)}
          />
          <Button
            onClick={handleTextImport}
            disabled={loading || !pastedText.trim()}
            className="w-full bg-blue-600 hover:bg-blue-700 text-white gap-2"
          >
            {loading ? (
              <>
                <Loader2 className="w-4 h-4 animate-spin" />
                Parsing text...
              </>
            ) : (
              <>
                <Linkedin className="w-4 h-4 fill-current" />
                Parse pasted profile
              </>
            )}
          </Button>
        </div>

        <div className="relative flex py-2 items-center">
          <div className="flex-grow border-t border-slate-200"></div>
          <span className="flex-shrink mx-4 text-slate-400 text-xs font-semibold uppercase">Or</span>
          <div className="flex-grow border-t border-slate-200"></div>
        </div>

        <div className="space-y-4">
          <Label>Upload LinkedIn PDF Export</Label>
          <div
            onClick={() => fileInputRef.current?.click()}
            className="border-2 border-dashed border-slate-300 rounded-lg p-6 text-center hover:border-blue-400 hover:bg-blue-50 transition cursor-pointer"
          >
            <input
              ref={fileInputRef}
              type="file"
              hidden
              accept=".pdf,.txt"
              onChange={handleFileSelect}
            />
            <div className="flex flex-col items-center gap-2">
              <Upload className="w-8 h-8 text-slate-400" />
              <p className="text-sm font-semibold text-slate-700">
                {file ? file.name : 'Select LinkedIn PDF Profile'}
              </p>
              <p className="text-xs text-slate-500">Supports PDF or plain text</p>
            </div>
          </div>

          {fileError && (
            <Alert variant="destructive" className="rounded-xl">
              <AlertCircle className="h-4 w-4" />
              <AlertDescription className="font-medium text-xs">{fileError}</AlertDescription>
            </Alert>
          )}

          {file && (
            <Button
              onClick={handleFileImport}
              disabled={loading}
              className="w-full bg-blue-600 hover:bg-blue-700 text-white gap-2"
            >
              {loading ? (
                <>
                  <Loader2 className="w-4 h-4 animate-spin" />
                  Extracting PDF...
                </>
              ) : (
                <>
                  <FileText className="w-4 h-4" />
                  Extract from {file.name}
                </>
              )}
            </Button>
          )}
        </div>
      </CardContent>
    </Card>
  );
}
